site_name: LUA Zenroom - blockchain language research in DECODE project
site_description: "Secure language design patterns for use in blockchain smart-contracts: restricted execution environments for deterministic, provable and distributed computing of algorithms."
site_author: Jaromil, DECODE project
theme: 'windmill'
repo_url: https://github.com/DECODEproject/lua-zenroom
pages:
  - Introduction: index.md
  - Design principles: design.md
  - API: api.md
